### PR TITLE
build: use autotools to build project

### PR DESCRIPTION
**Pull request by ricardomv**
To build for the first time use
autoreconf --install
./configure
make

After that you just need to make

### CODE REVIEW

**Comment by Lokaltog** [comment]
Awesome, thanks a lot!

**Comment by Lokaltog** [comment]
A couple of questions before I merge this, as I'm not familiar with autotools:
1. Why can't I just run ./configure (I haven't seen the requirement to run autoreconf --install in build instructions before)?
2. ./configure creates a metric ton of junk in the main directory, is there any way of cleaning this up automatically, or maybe having it in a subdirectory? It's cluttering up the main project folder pretty bad.

**Comment by ricardomv** [comment]
normally you don't need to do autoreconf --install because the ./configure file it is already included in the repo (whitch you can do, but every time you change configure.ac you need to "autoreconf" and add to git the new ./configure file and the new configure.ac . Now you just add what you change)

**Comment by Lokaltog** [comment]
Ah, I see, that seems reasonable.

Do you know if it's possible to put all the autogenerated stuff in a subfolder (e.g. build/)?

**Comment by ricardomv** [comment]
i need to do a bit of research about that, in the mean time you can use "git clean -fd"

**Comment by Lokaltog** [comment]
Merged in 159de5afb9d1130db23158766f5e0d6ec9ef5421

**Comment by ricardomv** [comment]
oh i just noticed i forgot to change the README

**Comment by ricardomv** [comment]
about the files created by configure and autoreconf i think you will have to live whith it. because "make" checks them and if they are not there it will ./configure again. the good news is you don't need to do ./configure if you change configure.am you can read the docs here https://www.gnu.org/software/automake/manual/automake.html#Hello-World

**Pull request closed without merging**
