### PR TITLE
Add the mpris widget

### PR DESCRIPTION
**Pull request by acrisci**
The mpris widget displays the artist and title for any media player that
implements the MPRIS DBus Interface Specification such as vlc, spotify,
mplayer, and others.

For more information on MPRIS:

http://specifications.freedesktop.org/mpris-spec/latest/

Pass "player_name" to the config to connect to
org.mpris.MediaPlayer2.[PLAYER] on your DBus session. If no player is
passed, the widget will choose the first mpris-enabled player that
becomes available to get metadata from.

### CODE REVIEW

**Comment by acrisci** [comment]
I thought you might appreciate the simplicity of the playerctl library instead of rewriting it into your project. The pkg-config file is new in v0.2.1. I have an AUR package for this version and a .deb file for version 0.2.0, which functions the same.

**Comment by acrisci** [comment]
We can do better than this implementation but I cannot figure out how to hook into your main loop without freezing the UI thread. I have events for all the important player actions like play, pause, and track change that you can connect to with `g_signal_connect`. See the documentation at http://dubstepdish.com/playerctl.

**Comment by Lokaltog** [comment]
Thanks, this looks great!

All widgets run in separate threads (so each widget is able to wait for events), but you can hook into the main thread by passing a callback to `g_idle_add` (which will run the callback in the main loop). This should only be used for non-blocking functions though. If you could describe how this could be implemented better I could maybe point you in the right direction.

There's a couple of things that it would be nice if you changed (to be consistent with the rest of the project):
- Rename the widget to `now_playing_mpris`
- Move the system header file include (`playerctl.h`) to `now_playing_mpris.h`

Other than that this looks good, I'll test it with an mpris-compatible player later today.

**Comment by acrisci** [comment]
It still freezes even with `g_idle_add` and without any blocking within the function added by `g_idle_add`. I'm not very familiar with the gtk threading model so I'm not sure how to resolve the issue.

What I would like to do is connect to the playerctl "metadata" signal, which fires when the track changes, and update the widget then.

It would also be nice to pass the entire metadata object to the widget view handler. The metadata is type GVariant.

**Comment by Lokaltog** [comment]
Does the playerctl provide a file descriptor that can be polled for changes? In that case you can attach this file descriptor to the same epoll instance that's used to wait for the thread interrupt signal. An example of this behavior is available in [widgets/desktops.c](https://github.com/Lokaltog/wkline/blob/develop/src/widgets/desktops.c#L141-149). Instead of blocking on `widget_epoll_wait_goto()`, you block on `epoll_wait` and check the type of data available on the file descriptor as done [here](https://github.com/Lokaltog/wkline/blob/develop/src/widgets/desktops.c#L153). What this does is basically unwrapping the `widget_epoll_wait_goto` convenience macro and checking for multiple types of available data on the file descriptor instead of just handling the interrupt signal.

If playerctl doesn't provide a file descriptor I don't think there's a good way of resolving this issue, as every widget thread needs to listen to the eventfd that provides the interrupt signal so widget threads can shut down safely when the main thread is interrupted.

---

If you want to pass a metadata object to the widget view handler you first need to convert it to a format that can be used with Javascript. I've [done this in desktops.c](https://github.com/Lokaltog/wkline/blob/develop/src/widgets/desktops.c#L74-88) by converting the data to a JSON string that's decoded in the theme, but you can also construct a JSCore object manually. I haven't tried that before and it may be a lot of annoying work, like casting every key and value to valid JS types. I find it much easier to construct JSON objects with jansson and it's totally fine if you want to go for that solution.

Anyways, I'm not sure how much work you want to do on this issue, if this is a bit too much I totally understand that and I can look into it myself later. Let me know what you think, I'd be happy to help you out with describing how the code is working if you want to implement these features.

**Comment by acrisci** [comment]
The player inherits from GObject so it is meant to be used with a GLib main loop. The only way I could think of to provide an fd is to make one with [GIO](https://developer.gnome.org/gio/stable/), which is I think more complexity than you want.

Given that you have GIO and the GMainLoop (and Gdk even), I think you should consider making more use of these tools because they are very powerful. If you like, I could assist you with some of the task of refactoring.

I will make the changes you originally specified and we can consider the event-driven approach at a later time.

**Comment by Lokaltog** [comment]
I'm not sure if I want to use glib more extensively, I'm getting the feeling glib tries to make C something it's not by adding stuff like `gpointer` instead of `void*` and all sorts of weird aliases, so it has left a bad impression. But I'm still a C noob so if you feel confident that using glib more extensively is the way to go (since we're depending on glib anyways) then it's fine with me. I don't know how I'd refactor blocking widgets to use the glib main loop (as opposed to running in separate threads?), so I'd definitely need some help refactoring it.

**Comment by Lokaltog** [comment]
I really want to add metadata like player status, times, etc. like the mpd widget, but I've merged it in the meantime and we can work on the other stuff later.

**Comment by acrisci** [comment]
Sure, I think you will find GIO much easier to work with than raw POSIX file descriptors. I think you will find everything you are doing will become much easier.

I'm watching the repo, so make an issue and I'll jump in.

**Pull request merged**
