### PR TITLE
widgets/volume: if channel is muted set volume to 0

### PR DESCRIPTION
**Pull request by ricardomv**
also, i am getting errors when updating the volume, do you know what's the problem? "*\* Message: console message: http://lokaltog.github.io/wkline-theme-default/ @1: Could not update widget: TypeError: undefined is not an object (evaluating 'this.widgets[a].update')"

### CODE REVIEW

**Comment by Lokaltog** [comment]
Do you only receive it when changing the volume? I haven't pushed the notification-daemon widget to the theme file yet, so if your volume control sends libnotify notifications it could cause this error.

**Comment by Lokaltog** [comment]
Merged in 598652a45bfbfb33b5cd6e65f606f0769673d4b2

**Comment by ricardomv** [comment]
ah  yes that's it for sure

**Comment by Lokaltog** [comment]
Hm, I think that may actually become a problem with the current notification daemon implementation. I didn't consider notification categories, and the category isn't sent to the theme file so there's no way to display volume change notifications differently. That should probably be fixed before updating the theme.

**Pull request closed without merging**
