### PR TITLE
Add support for passwordcommand in email_imap.

### PR DESCRIPTION
**Pull request by Andersbakken**
Hi. I wrote a patch be able to run a process to get the password for the email_imap exension (since I didn't want to put my password in the config file). I can now run a little script to use gpg to extract the password. To achieve this I had to have a general purpose process class which I also added. I was wondering if you would be willing to merge. 

To use I just do this:

...
        {
            "module": "email_imap",
            "config": {
                "passwordcommand": "/path/to/script/that/runs/gpg",
                "username": "username@gmail.com"
            }
        }
...

Foroevrig regner jeg med at du er Norsk :-)

### CODE REVIEW

**Comment by Lokaltog** [comment]
Very nice, thanks a lot! I'll have to do some minor cleanup of code style to match the rest of the project before merging, but this looks great, the process stuff could possibly be used for other things as well (e.g. insert the output from a command into a widget). I'll review it and merge this along with the other pending PRs when I have time. I'm a bit swamped with work at the moment but I'll look into this as soon as possible!

**Comment by Andersbakken** [comment]
Sounds good. I was thinking a general purpose process class might come in
handy. It might even be helpful to make it async so that a external process
could keep state.

**Comment by Lokaltog** [comment]
I'm using `pass` to store my passwords, and it would be awesome to be able to just specify something like `/usr/bin/pass my-gmail-password` as the password command, but it appears the command doesn't accept arguments? Is it possible to refactor so the password command can accept arguments?

**Comment by Andersbakken** [comment]
Hi Kim

It's actually supposed to accept multiple args. I didn't do it using an
array though (which might have been the preferred way).

E.g.

You should be able to do:

...
"password_command": "/usr/bin/pass my-gmail-password"
...

It will tokenize (no support for quoting either). Does this not work for
you?

Anders

**Comment by Lokaltog** [comment]
I tried it, but it didn't work. I figured it was because argv[1] got overwritten [here](https://github.com/Lokaltog/candybar/commit/e103c66e879d46c6b9a13f186a45abec317caecb#diff-3e4dd6ca3360ceb60da41ac3bca64b01L213), and when I removed that block it worked fine. Please let me know if this has any unintended side-effects or if I should spawn processes differently.

**Pull request merged**
