### PR TITLE
widgets/now_playing_mpris: event-driven updates

### PR DESCRIPTION
**Pull request by acrisci**
Use the player "metadata" event rather than a polling interval for
updating the widget. This event should be emitted when the track
changes.

If no player is passed, the widget will poll DBus for players every
second until it finds one.

### CODE REVIEW

**Comment by acrisci** [comment]
This may introduce some quirks that I may have to deal with on the library level, but as Linus says, release early release often.

For one, not all players give me an empty metadata object when they close (vlc does, spotify does not). This may require an extra event for when the player quits, which I think is in the spec.

And also, some players like vlc will open multiple DBus names for each instance. If a name is not specified in the config and the player connects to an instance name, once the instance quits, the player will not show metadata for the new instance.

I recommend that you advise people to pass a player name if they can, because the case where no player is specified cannot be done completely right.

**Comment by Lokaltog** [comment]
Looks good, event-driven is much better than polling. I'll merge it, but we should look at including other metadata, it would be ideal if this widget could reuse the existing "now playing" functionality in the theme, but it requires stuff like player status and play times to work.

Regarding player names, the way I've handled mandatory config options in other widgets is to have the default be empty, and log an error and disable the widget (return from the main widget function) if the user doesn't specify the config option. I think this is better than attempting to do something that's not going to work anyways. What do you think?

**Comment by Lokaltog** [comment]
I'm not sure when the `on_metadata` callback is executed, but in the case of other event-driven widgets I always execute `update_widget()` before entering the wait loop to ensure that some initial data is passed to the widget. An example is the desktop widget: if you start candybar you wouldn't see the desktop list until you switch desktops or another event is emitted by XCB, so `update_widget()` is executed first to show the user the current state of the desktop list before waiting for changes.

**Comment by acrisci** [comment]
> it would be ideal if this widget could reuse the existing "now playing" functionality in the theme, but it requires stuff like player status and play times to work.

There are some [metadata guidelines](http://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/) that should be enough to reuse the view. We also have a [position property](http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Position) and pretty much everything you can think of.

> it would be ideal if this widget could reuse the existing "now playing" functionality in the theme

What about having one mediaplayer widget that chooses the correct backend based on the player name?

> I always execute update_widget() before entering the wait loop

I tried that and ran into problems. I didn't put too much effort into resolving that issue because I think it would be rare for someone to start the player before the bar under normal use conditions.

> Regarding player names, the way I've handled mandatory config options in other widgets is to have the default be empty

Having a single mediaplayer widget might justify this. Ideally it should just display metadata for whatever player the person is listening to, but doing that correctly is complex. I think someone who uses multiple players is on the rare side, but not impossible.

**Comment by Lokaltog** [comment]
Merged in b0e6701ab7e55ec7701be271264ce73e8c436043

**Pull request closed without merging**
