### PR TITLE
build: compile .c files separately

### PR DESCRIPTION
**Pull request by ricardomv**
the header files in the widgets are a bit of a mess but i can fix that tomorow, anyway it builds fine and now when you change a file only that file will be compiled.

btw, it's a bad practice to include a .c includes are for header files. Now you just need to put the prototype of the function in the header, include the header in the .c you call the function and the linker will do all the work

### CODE REVIEW

**Comment by Lokaltog** [comment]
Thanks a lot for this, I really appreciate the help! wkline is the first project I've ever done in C, so I know little about best practices for project organization or anything like that, and I had a feeling there was a lot of room for improvement regarding the header files.

**Comment by ricardomv** [comment]
You're welcome, yeah i saw that and i'm glad i can help. If you need help send me an e-mail. Now you need to help me with github, you made a commit do i need to rebase my fork?

**Comment by ricardomv** [comment]
For the structure i was thinking every client has his external libraries inside his .h file and every widget gets a #include "widgets.h". if you have a structure in a widget you need to use in wkline.c you put the .h of that widget in the widgets.h. And i was thinking in renaming the lib folder to utils and move the log functions there

**Comment by Lokaltog** [comment]
I'm doing some refactoring on the data format passed to the webview, I'll just cherry-pick this commit when I'm done with that.

Renaming lib to utils and moving the log function sounds good!

**Pull request closed without merging**
